### ISSUE TITLE
Implement Ticketmaster API functionality

### ISSUE THREAD

**Issue by lzapson** [lzapson/Gig-Compass#5]

**Comment by johnlatona** [comment]
Name of Event: 

response.embedded.events[i].name

Name of Venue:

response.embedded.events[i].embedded.venues.Array[i].name

Address of Venue

response.embedded.events[i].embedded.venues[i].address.line#
response.embedded.events[i].embedded.venues[i].city.name
response.embedded.events[i].embedded.venues[i].state.stateCode
response.embedded.events[i].embedded.venues[i].postalCode

Date

response.embedded.events[i].dates.start.localDate

Time

response.embedded.events[i].dates.start.localTime

Location:

	Latitude:
	response.embedded.events[i].embedded.venues[i].location.latitude

	Longitude:
	response.embedded.events[i].embedded.venues[i].location.longitude
